version: '3.3' 
services:
  jenkins:
     image: jenkinsci/blueocean
     restart: always
     privileged: true
     user: root
     ports:
      - 8083:8080
      - 50000:50000
     container_name: jenkins_blueocean-docker
     volumes:
      - /home/jenkinsdocker:/var/jenkins_home 
      - /var/run/docker.sock:/var/run/docker.sock
